age=input("how old are you?")
name=input("what is your name?")
city=input("which city yiu belong from?")
####################
print("how old are you?")
age=input()
print("which city you belong from?")
city=input()
print(f"so you age is {age} and your city {city}")
###################333
print("how old are you?", end='')
age=input()
print("which city you belong from?",end='')
city=input()
print(f"so you age is {age} and your city {city}")